apiVersion: v1
kind: Service
metadata:
  namespace: login
  labels:
    app: login
  name: login
spec:
  ports:
  
    - protocol: TCP
      port: 8087
      targetPort: 8087
   
   
  selector:
    app: login
  type: ClusterIP
